# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Biubiubomb  # 博客标题
email: 154406260@qq.com  # 你的邮箱
description: >
  biubiu~发射爱~~bomb
logo: "assets/images/logo.jpg"    #自定义 logo
# baseurl: "/amplify" # 重要：如果你绑定了自定义域名或使用了自己的用户名作为项目名，请删除本行并修改下一行
url: "http://biubiubomb.coding.me" # 如果你绑定了自定义域名或使用了自己的用户名作为项目名，请修改本行为你的域名
paginate:	2 # 每页显示文章数量

name: 'biubiubomb'   # 你的昵称
bio: >
  
author_image: "assets/images/author.jpg"  #个人头像
twitter_username: 
github_username: biubiubomb
coding_username: biubiubomb

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
